### ISSUE TITLE
Overlapping elements in Firefox

### ISSUE THREAD

**Issue by vlamacko** [azer/afrikaradyo.com#2]
![firefox_2018-07-09_14-03-22](https://user-images.githubusercontent.com/11365038/42449440-0009de06-8381-11e8-9721-b4c914741654.jpg)

## Browser
Firefox 61.0.1
Safe mode (all add-ons disabled)

I hope this helps ☺️. Thanks for the music.

**Comment by azer** [comment]
fixed! thanks :)
